
MYDISK_THEMES = {
    "mydiskdark": {
        "type": "dark",
        "colors": {
            "primary":   "#406793",
            "secondary": "#282828",
            "success":   "#008000",
            "info":      "#5332b6",
            "warning":   "#f39c12",
            "danger":    "#dd2f1c",
            "light":     "#ADB5BD",
            "dark":      "#303030",
            "bg":        "#222222",
            "fg":        "#ffffff",
            "selectbg":  "#555555",
            "selectfg":  "#ffffff",
            "border":    "#222222",
            "inputfg":   "#ffffff",
            "inputbg":   "#2f2f2f",
            "active":    "#1F1F1F",
        },
    },
    "mydisk_obsidian": {
        "type": "dark",
        "colors": {
            "primary":   "#000000",   
            "secondary": "#006E2B",   
            "success":   "#00E676",   
            "info":      "#1C1F2B",   
            "warning":   "#FFD740",   
            "danger":    "#FF5252",  
            "light":     "#B0BEC5",  
            "dark":      "#0D0F17",   
            "bg":        "#12151F",   
            "fg":        "#E8EEF7",   
            "selectbg":  "#0D3D35",   
            "selectfg":  "#E8EEF7",   
            "border":    "#1E2235",   
            "inputfg":   "#E8EEF7",  
            "inputbg":   "#161925",  
            "active":    "#1A1E2C",   
        },
    },
}